# Generated by Django 4.1.1 on 2022-09-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votofeminino', models.PositiveIntegerField()),
                ('votodemenores', models.PositiveIntegerField()),
                ('votodeanalfabetos', models.PositiveIntegerField()),
                ('votodenegros', models.PositiveIntegerField()),
                ('votobranconulo', models.PositiveIntegerField()),
                ('votodecabresto', models.PositiveIntegerField()),
                ('aprovou', models.PositiveIntegerField()),
                ('naoaprovou', models.PositiveIntegerField()),
            ],
        ),
    ]
