# Generated by Django 4.1.1 on 2022-09-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoAprovou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovou', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotoBrancoNulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votobranconulo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotoDeAnalfabetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votodeanalfabetos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotoDeCabresto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votodecabresto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotoDeMenores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votodemenores', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotoDeNegros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votodenegros', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotoFeminino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votofeminino', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotoNaoAprovou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naoaprovou', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Votacao',
        ),
    ]
